name: Perform Checks on Committed Go Code

on:
  push:
    branches-ignore: [ main, staging ]

jobs:
  builds:
  
    runs-on:
      ubuntu-latest

    env:
      SERVER_PORT: ${{ secrets.DEV_SERVER_PORT }}
      BAXUS_ORIGIN: ${{ secrets.DEV_BAXUS_ORIGIN }}
      DB_USER: ${{ secrets.DEV_DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      DB_NET: ${{ secrets.DEV_DB_NET }}
      DB_ADDR: ${{ secrets.DEV_DB_ADDR }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'

      - name: Run Go code
        run: go run app/main.go

      - name: Lint Go code
        uses: golangci/golangci-lint-action@v2
        with:
          # Version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version 
          version: latest