name: Perform Checks on Committed Go Code

on:
  push:
    branches-ignore: [ main ]

jobs:
  builds:
    runs-on:
      ubuntu-latest
    
    steps:
      - name: Checkout repo
      uses: actions/checkout@v2

      - name: Set up Go environment
      uses: uses: actions/setup-go@v2
      with:
        go-version: '1.16.1'

      - name: Run Go code
      run: go run app/main.go -local

      - name: Lint Go code
        uses: golangci/golangci-lint-action@v2
        with:
          # Version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest