name: Build production database from newest changelog

# Will run whenever a commit is pushed to main
# This should only be from the staging branch!
on:
  push:
    branches: [ add-liquibase-gh-action ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:

      # Check out the main branch in the runner
      - name: Checking out the main branch
        uses: actions/checkout@v2
        
      - run: echo "Successfully checked out master branch"

    # Build the database using the latest master changelog 
      - name: Building the production database from the Liquibase changelog
        uses: liquibase/liquibase-github-action@v3
        with:
          operation: 'update'
          changeLogFile: 'changelog_master.xml'
          username: ${{ secrets.DEV_DB_USERNAME }}
          password: ${{ secrets.DEV_DB_PASSWORD }}
          url: 'jdbc:mysql://baxus.c3tf20wv9p1c.us-east-2.rds.amazonaws.com:3306/dev'
        
      - run: echo "Successfully built production database"

      - name: Updating latest production database version tag
        uses: liquibase/liquibase-github-action@v3
        with:
          operation: 'tag'
          changeLogFile: 'changelog_master.xml'
          username: ${{ secrets.PROD_DB_USERNAME }}
          password: ${{ secrets.PROD_DB_PASSWORD }}
          url: 'jdbc:mysql://baxus.c3tf20wv9p1c.us-east-2.rds.amazonaws.com:3306/dev'
          tag: 'version1'

      - run: echo "Successfully updated version tag"