name: Build production database from newest changelog

# Will run whenever a commit is pushed to main
# This should only be from the staging branch!
on:
  push:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:

      # Check out the main branch in the runner
      - name: Checking out the main branch
        uses: actions/checkout@v2
        
      - run: echo "Successfully checked out master branch"

    # Build the database using the latest master changelog 
      - name: Building the database from the Liquibase changelog
        uses: liquibase/liquibase-github-action@v3
        with:
          operation: 'update'
          classpath: '../db_changelogs/'
          changeLogFile: 'changelog_master.xml'
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          url: ${{ secrets.DB_URL }} 
        
      - run: echo "Successfully built production database"

      - name: Updating latest database version tag
        uses: liquibase/liquibase-github-action@v3
        with:
          operation: 'tag'
          classpath: '../db_changelogs/'
          changeLogFile: 'changelog_master.xml'
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          url: ${{ secrets.DB_URL }}
          tag: 'version1'

      - run: echo "Successfully updated version tag"