name: Deploy repo to Google App Engine cors-test-branch Project

on:
  push:
    branches: [ add-appengine-gh-action ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Checking out the main branch
      uses: actions/checkout@v2

    - name: Setting app.yaml values
      uses: golang-enthusiast/app-yaml-env-compiler@v1.0
      env:
        SERVER_PORT: ${{ secrets.DEV_SERVER_PORT }}
        BAXUS_ORIGIN: ${{ secrets.DEV_BAXUS_ORIGIN }}
        DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
        DB_NET_TYPE: ${{ secrets.DEV_DB_NET_TYPE }}
        DB_NET_ADDR: ${{ secrets.DEV_DB_NET_ADDR }}

    - name: Authenticating Service Account with Workload Identity Federation
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/3835018965/locations/global/workloadIdentityPools/gh-beta-service-prod-pool/providers/gh-beta-service-prod-provider'
        service_account: 'github-beta-service-deployment@baxus-prod-service.iam.gserviceaccount.com'

    - name: Deploying to App Engine
      uses: 'google-github-actions/deploy-appengine@v0' 